// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateOrderInput struct {
	CustomerID int     `json:"customerId"`
	Amount     float64 `json:"amount"`
	Status     string  `json:"status"`
}

type Mutation struct {
}

type Order struct {
	ID         string  `json:"id"`
	CustomerID int     `json:"customerId"`
	Amount     float64 `json:"amount"`
	Status     string  `json:"status"`
	CreatedAt  string  `json:"createdAt"`
}

type Query struct {
}
